from presentacion.menu_principal import menu_principal
from presentacion.control_libro import agregar_libro,listado_libros,modificar_libro,eliminar_libro
from presentacion.control_usuario import agregar_usuario,listar_usuario,modificar_usuario,eliminar_usuario
from presentacion.solicitud_datos import solicitar_dato,solicitar_datos_libro,nuevos_datos_libro,solicitar_datos_usuario